// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI5clwP0BpKj0glwlXHPTQfQb4NhtKcZo',
    appId: '1:74600573757:web:0710fd655c1921dd9d7354',
    messagingSenderId: '74600573757',
    projectId: 'quick-notes-projet-joshua',
    authDomain: 'quick-notes-projet-joshua.firebaseapp.com',
    storageBucket: 'quick-notes-projet-joshua.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSXBH6sX20vWStmFsl0-6BbYV2WX82vc',
    appId: '1:74600573757:android:472dc5e3fb13b2dd9d7354',
    messagingSenderId: '74600573757',
    projectId: 'quick-notes-projet-joshua',
    storageBucket: 'quick-notes-projet-joshua.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ2uRlQUum_v5X5OoP1NAYXDOE2PC9oVQ',
    appId: '1:74600573757:ios:60d19fb4141659989d7354',
    messagingSenderId: '74600573757',
    projectId: 'quick-notes-projet-joshua',
    storageBucket: 'quick-notes-projet-joshua.firebasestorage.app',
    iosBundleId: 'com.jugajoshua.quicknote',
  );
}
